# model: openrouter/deepseek/deepseek-r1:free
# model: gemini/gemini-2.5-pro-preview-05-06 
model: gemini/gemini-2.5-flash-preview-05-20
dark-mode: true
auto-commits: false
# multiline: true
read: CONVENTIONS.md

alias:
  - r1:openrouter/deepseek/deepseek-r1:free
  - claude:openrouter/anthropic/claude-3.7-sonnet
  - o3-mini:openrouter/openai/o3-mini

