import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[font]
# normal = { family = "RobotoMono Nerd Font", style = "Regular" }
# normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
# normal = { family = "FiraCode Nerd Font", style = "Light" }
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }
size = 20 

[cursor]
style = { shape = "Block" }

[env]
TERM = "xterm-256color"
